using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Net.Http;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using System.Threading;
using System.Threading.Tasks;
using Plugin.Connectivity;
using Plugin.Connectivity.Abstractions;
using Refit;
using iFit.Api.Zendesk.DataObjects;
using iFit.Api.Zendesk.RefitInternalGenerated;

[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: TargetFramework(".NETStandard,Version=v2.1", FrameworkDisplayName = "")]
[assembly: AssemblyCompany("iFit Mobile")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyDescription("iFit Zendesk API")]
[assembly: AssemblyFileVersion("2.1.0")]
[assembly: AssemblyInformationalVersion("1.0.0")]
[assembly: AssemblyProduct("iFit.Api.Zendesk")]
[assembly: AssemblyTitle("iFit.Api.Zendesk")]
[assembly: AssemblyVersion("2.1.0.0")]
namespace iFit.Api.Zendesk
{
	public interface IZendeskApi
	{
		[Post("/api/v2/requests")]
		Task<Request.CreateRequestResponse> CreateRequest([Body] Request request, CancellationToken token = default(CancellationToken));
	}
	public class ConnectivityException : Exception
	{
		public ConnectivityException(string message = null)
			: base(message)
		{
		}
	}
	public class ConnectivityTryAgainLaterException : Exception
	{
		public ConnectivityTryAgainLaterException(string message = null)
			: base(message)
		{
		}
	}
	public interface IZendeskApiService
	{
		IZendeskApi Service { get; }
	}
	public class ZendeskApiService : IZendeskApiService
	{
		public const string Url = "https://ifit.zendesk.com";

		private readonly IZendeskApi zendeskApi;

		public IZendeskApi Service => zendeskApi;

		public ZendeskApiService(string url = "https://ifit.zendesk.com")
		{
			HttpClient client = new HttpClient
			{
				BaseAddress = new Uri(url)
			};
			zendeskApi = RestService.For<IZendeskApi>(client);
		}
	}
	[ExcludeFromCodeCoverage]
	[DebuggerNonUserCode]
	[Preserve]
	[Obfuscation(Exclude = true)]
	internal class AutoGeneratedIZendeskApi : IZendeskApi
	{
		private readonly IRequestBuilder requestBuilder;

		public HttpClient Client { get; protected set; }

		public AutoGeneratedIZendeskApi(HttpClient client, IRequestBuilder requestBuilder)
		{
			Client = client;
			this.requestBuilder = requestBuilder;
		}

		Task<Request.CreateRequestResponse> IZendeskApi.CreateRequest(Request request, CancellationToken token)
		{
			object[] arg = new object[2] { request, token };
			return (Task<Request.CreateRequestResponse>)requestBuilder.BuildRestResultFuncForMethod("CreateRequest", new Type[2]
			{
				typeof(Request),
				typeof(CancellationToken)
			})(Client, arg);
		}
	}
}
namespace iFit.Api.Zendesk.RefitInternalGenerated
{
	[ExcludeFromCodeCoverage]
	[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
	internal sealed class PreserveAttribute : Attribute
	{
		public bool AllMembers;

		public bool Conditional;
	}
}
namespace iFit.Api.Zendesk.DataObjects
{
	public class Request
	{
		public class Requester
		{
			public string name { get; set; }

			public string email { get; set; }
		}

		public class Comment
		{
			public string body { get; set; }
		}

		public class CustomField
		{
			public long id { get; set; }

			public string value { get; set; }
		}

		public class RequestBody
		{
			public long ticket_form_id { get; set; }

			public Requester requester { get; set; }

			public string subject { get; set; }

			public string[] tags { get; set; }

			public Comment comment { get; set; }

			public List<CustomField> custom_fields { get; set; }
		}

		public class CreateRequestResponse
		{
			public class Request
			{
				public string url { get; set; }

				public int id { get; set; }
			}

			public Request request { get; set; }
		}

		public const string AnonymousName = "anon";

		private const long IfitUserCustomFieldId = 20963599L;

		private const long ZenDeskPhoneNumberFieldId = 360004544012L;

		private const long ZenDeskAddressFieldId = 360004543832L;

		private const long ZenDeskCityFieldId = 360004544392L;

		private const long ZenDeskStateFieldId = 360004544412L;

		private const long ZenDeskZipFieldId = 360004590171L;

		private const long ZenDeskEquipmentSelectionFieldId = 360047381671L;

		public RequestBody request { get; protected set; }

		public Request(string username, string name, string email, string equipmentType, string description, string feedback)
		{
			request = new RequestBody
			{
				ticket_form_id = 360003162152L,
				requester = new Requester
				{
					name = name,
					email = email
				},
				comment = new Comment
				{
					body = feedback
				},
				subject = username + ": " + description,
				tags = new string[1] { "feedback" },
				custom_fields = new List<CustomField>
				{
					new CustomField
					{
						id = 20963599L,
						value = username
					},
					new CustomField
					{
						id = 360004544012L,
						value = "1234567890"
					},
					new CustomField
					{
						id = 360004543832L,
						value = "unknown"
					},
					new CustomField
					{
						id = 360004544392L,
						value = "unknown"
					},
					new CustomField
					{
						id = 360004544412L,
						value = "unknown"
					},
					new CustomField
					{
						id = 360004590171L,
						value = "unknown"
					},
					new CustomField
					{
						id = 360047381671L,
						value = equipmentType
					}
				}
			};
		}

		public static async Task<CreateRequestResponse> Create(string username, string name, string email, string equipmentType, string subject, string feedback, IZendeskApiService zendeskApi = null, IConnectivity connectivity = null)
		{
			if (connectivity == null)
			{
				connectivity = CrossConnectivity.Current;
			}
			if (!connectivity.IsConnected)
			{
				throw new ConnectivityException("Not connected on Zendesk create request call");
			}
			IZendeskApiService obj = zendeskApi ?? new ZendeskApiService();
			Request request = new Request(username, name, email, equipmentType, subject, feedback);
			return await obj.Service.CreateRequest(request);
		}
	}
}
