using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using ModernHttpClient;
using Newtonsoft.Json;
using Plugin.Connectivity;
using Refit;
using iFit.Api.MaxMind.DataObjects;
using iFit.Api.MaxMind.RefitInternalGenerated;
using iFit.Api.Support;

[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: TargetFramework(".NETStandard,Version=v2.1", FrameworkDisplayName = "")]
[assembly: AssemblyCompany("iFit Mobile")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyDescription("iFit MaxMind Api logic")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0")]
[assembly: AssemblyProduct("iFit.Api.MaxMind")]
[assembly: AssemblyTitle("iFit.Api.MaxMind")]
[assembly: AssemblyVersion("1.0.0.0")]
namespace iFit.Api.MaxMind
{
	public class AuthenticatedHttpClientHandler : NativeMessageHandler
	{
		private readonly string basicAuth;

		public AuthenticatedHttpClientHandler(string basicAuth)
		{
			this.basicAuth = basicAuth;
		}

		protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
		{
			if (!CrossConnectivity.Current.IsConnected)
			{
				throw new ConnectivityException("no internet connection");
			}
			AuthenticationHeaderValue authorization = request.Headers.Authorization;
			if (authorization != null && authorization.Scheme == "Basic")
			{
				request.Headers.Authorization = new AuthenticationHeaderValue(authorization.Scheme, basicAuth);
			}
			return await ((HttpClientHandler)this).SendAsync(request, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
		}
	}
	public interface IMaxMindApi
	{
		[Get("/country/me")]
		[Headers(new string[] { "Authorization: Basic" })]
		Task<CountryResponse> GetCountryResponse();
	}
	public interface IMaxMindApiService
	{
		IMaxMindApi Service { get; }
	}
	public class MaxMindApiService : IMaxMindApiService
	{
		public const string Url = "https://geoip.maxmind.com/geoip/v2.1";

		public readonly string[] AccountIdKeys = new string[5] { "8", ":", "6", "3", "0" };

		public readonly string[] LicenseKeys = new string[3] { "52Wj", "EIF5", ":nt3" };

		public IMaxMindApi Service { get; }

		public MaxMindApiService(string url = "https://geoip.maxmind.com/geoip/v2.1", string accountId = null, string licenseKey = null)
		{
			accountId = accountId ?? AccountIdKeys.TransformString();
			licenseKey = licenseKey ?? LicenseKeys.TransformString();
			RefitSettings settings = new RefitSettings
			{
				ContentSerializer = new NewtonsoftJsonContentSerializer(new JsonSerializerSettings
				{
					ContractResolver = new SnakeCasePropertyNamesContractResolver(),
					NullValueHandling = NullValueHandling.Ignore
				})
			};
			HttpClient client = new HttpClient(new AuthenticatedHttpClientHandler(Convert.ToBase64String(Encoding.UTF8.GetBytes(accountId + ":" + licenseKey))))
			{
				BaseAddress = new Uri(url)
			};
			Service = RestService.For<IMaxMindApi>(client, settings);
		}
	}
	[ExcludeFromCodeCoverage]
	[DebuggerNonUserCode]
	[Preserve]
	[Obfuscation(Exclude = true)]
	internal class AutoGeneratedIMaxMindApi : IMaxMindApi
	{
		private readonly IRequestBuilder requestBuilder;

		public HttpClient Client { get; protected set; }

		public AutoGeneratedIMaxMindApi(HttpClient client, IRequestBuilder requestBuilder)
		{
			Client = client;
			this.requestBuilder = requestBuilder;
		}

		Task<CountryResponse> IMaxMindApi.GetCountryResponse()
		{
			object[] arg = new object[0];
			return (Task<CountryResponse>)requestBuilder.BuildRestResultFuncForMethod("GetCountryResponse", new Type[0])(Client, arg);
		}
	}
}
namespace iFit.Api.MaxMind.RefitInternalGenerated
{
	[ExcludeFromCodeCoverage]
	[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
	internal sealed class PreserveAttribute : Attribute
	{
		public bool AllMembers;

		public bool Conditional;
	}
}
namespace iFit.Api.MaxMind.DataObjects
{
	public class CountryResponse
	{
		public class CountryInfo
		{
			public string IsoCode { get; set; }
		}

		public CountryInfo Country { get; set; }
	}
}
